---
# tasks file for database
- name: Install required packages
  apt: 
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - python3-psycopg2
    - postgresql

- name: Replacing /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"

- name: Create database {{ pg_db }} 
  community.postgresql.postgresql_db:
    name: "{{ pg_db }}"

- name: Create user {{ pg_user }}
  community.postgresql.postgresql_user:
    db: "{{ pg_db }}"
    name: "{{ pg_user }}"
    password: "{{ pg_password }}"

- name: Copy SQL script into nodes
  copy:
    src: init.sql
    dest: /tmp/init.sql

- name: Run SQL script
  community.postgresql.postgresql_script:
    db: postgres
    path: /tmp/init.sql
    named_args:
      id_user: 0
    encoding: UTF-8  

- name: Restart postgresql service
  service:
    name: postgresql
    state: restarted

